# Python DB Connections process
1. **Installing PyMySQL**:
   - The first block shows the command `pip install pymysql` to install the PyMySQL library. This allows Python to communicate with MySQL databases.

2. **Importing PyMySQL**:
   - The next block imports the installed library using `import pymysql`.

3. **Connecting to the MySQL Database**:
   - The connection to the MySQL database is established using `pymysql.connect()`. The parameters include:
     - `host`: The URL of the MySQL database (`rohan-mysql-db-rohanbdconnections.c.aivencloud.com`).
     - `user`: Username (`avanadmin`).
     - `password`: Password for authentication.
     - `port`: Port number (19414).
     - `database`: The name of the database (`rohanbd`).
   - A success message `"connect with database successfully"` is printed upon successful connection.

4. **Creating a Cursor**:
   - A cursor object `curs` is created using `con.cursor()`. Cursors allow executing SQL queries from Python.

5. **Executing an SQL Query**:
   - The cursor executes a query to select all records from the `accounts` table with `curs.execute("select * from accounts")`.
   - The query returns `20`, indicating the number of rows returned from the table.

6. **Fetching and Printing Data**:
   - The data from the query is fetched using `curs.fetchall()`, and a loop is used to print each row of the fetched data.

In [ ]:
pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 2.3 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [ ]:
import pymysql

In [ ]:
con=pymysql.connect(host="rohan-mysql-db-rohandbconnections.c.aivencloud.com",user="avnadmin",password="AVNS_jLvqn4KtNKeQMfTv6yn",port=19414,database="rohandb")
print('connect with database successfully')

connect with database successfully

In [ ]:
curs=con.cursor()

In [ ]:
curs.execute("select * from accounts")

20

In [ ]:
data=curs.fetchall()
for datas in data:
  print(datas)

(1001, 'Amit Kumar', 'Savings', 50000.5)
(1002, 'Neha Sharma', 'Current', 150001.0)
(1003, 'Rahul Singh', 'Savings', 25000.0)
(1004, 'Priya Desai', 'Current', 75000.2)
(1005, 'Vikas Patel', 'Savings', 32000.0)
(1006, 'Manish Agarwal', 'Current', 98000.5)
(1007, 'Suman Rao', 'Savings', 40000.0)
(1008, 'Anjali Nair', 'Current', 120000.0)
(1009, 'Rakesh Gupta', 'Savings', 60000.8)
(1010, 'Pooja Iyer', 'Current', 110001.0)
(1011, 'Vijay Reddy', 'Savings', 54000.9)
(1012, 'Sneha Kapoor', 'Current', 102500.0)
(1013, 'Rohit Verma', 'Savings', 70000.0)
(1014, 'Kavita Joshi', 'Current', 130000.0)
(1015, 'Nitin Saxena', 'Savings', 55000.5)
(1016, 'Meena Khanna', 'Current', 99000.9)
(1017, 'Suresh Yadav', 'Savings', 46000.1)
(1018, 'Deepa Mehta', 'Current', 118000.0)
(1019, 'Rajiv Bhatia', 'Savings', 52000.7)
(1020, 'Alok Chatterjee', 'Current', 123500.0)

In [ ]:
con.close()